<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Enums\RolesEnum;
use App\Models\DoctorInfo;
use App\Models\DoctorSchedules;
use App\Models\User;
use Carbon\Carbon;
use Tests\TestCase;

class AppointmentTest extends TestCase
{

    protected $patient;
    protected $doctor;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');

        $this->patient = User::factory(1)->create()->each(function ($user) {
            $user->assignRole(RolesEnum::Patients->value);
        })->first();

        $this->doctor = User::factory(1)->create()->each(function ($user) {
            $user->assignRole(RolesEnum::DOCTOR->value);
            DoctorInfo::factory(1)->create(['user_id' => $user->id]);
            DoctorSchedules::factory(7)->create([
                'doctor_id' => $user->id,
            ]);
        })->first();


    }

    /**
     * A basic test example.
     */
    public function test_patient_can_login(): void
    {
        $this->assertNotNull($this->patient->first()); // Check if user with ID 18 exists
        $this->actingAs($this->patient);
        $this->assertAuthenticatedAs($this->patient);

    }

    /**
     * A basic test example.
     */
    public function test_appointment_can_not_create__when_doctor_is_not_available(): void
    {
        $this->actingAs($this->patient->first());
        $response = $this->get(route('appointment.create'));
        $response->assertStatus(200);
         $response = $this->post(route('appointment.create'),[
            'first_name' => 'John',
            'last_name' => 'Test',
            'email' => fake()->email,
            'mobile' => '1233',
            'doctor' => $this->doctor->id,
            'date' => Carbon::now()->endOfWeek()->format("Y-m-d"),
          ]);

        $this->assertTrue($this->assertToastMessage('error','Doctor is not available on this date'));
        $response->assertRedirect(route('appointment.create'));

    }


    /**
     * A basic test example.
     */
    public function test_appointment_can_create(): void
    {
        $this->actingAs($this->patient->first());
        $response = $this->get(route('appointment.create'));
        $response->assertStatus(200);
         $response = $this->post(route('appointment.create'),[
            'first_name' => 'John',
            'last_name' => 'Test',
            'email' => fake()->email,
            'mobile' => '1233',
            'doctor' => $this->doctor->id,
            'date' => Carbon::today()->format('Y-m-d'),
          ]);

        $response->assertRedirect(route('appointment.index'));

    }


    protected function assertToastMessage($type,$message):bool
    {
        $toasts = session('laravel-toaster-magic::messages');
        if (is_null($toasts)) {
            return false;
        }

      return collect($toasts)->whereIn('type',$type)->whereIn('message',$message)->count() > 0 ;
    }


}
