<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Enums\RolesEnum;
use App\Models\DoctorInfo;
use App\Models\DoctorSchedules;
use App\Models\User;
use Database\Factories\DoctorSchedulesFactory;
use Tests\TestCase;

class DoctorTest extends TestCase
{

    protected $doctor;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->artisan('db:seed');
        $this->doctor = User::factory(1)->create()->each(function ($user) {
            $user->assignRole(RolesEnum::DOCTOR->value);
        })->first();
     }

    /**
     * A basic test example.
     */
    public function test_create_a_doctor(): void
    {

        $this->assertDatabaseHas(User::class,[
            'id' => $this->doctor->id,
        ]);

    }

    /**
     * A basic test example.
     */
    public function test_create_doctor_info(): void
    {

        $this->assertNotNull($this->doctor);
        $this->actingAs($this->doctor);

        $response = DoctorInfo::factory()->create([
            'user_id' => $this->doctor->id,
        ]);


        $this->assertNotNull($response);
        $this->assertDatabaseHas('doctor_infos', [
            'user_id' => $this->doctor->id,
        ]);
    }


    /**
     * A basic test example.
     */
    public function test_create_doctor_schedules(): void
    {

        DoctorSchedules::factory(7)->create([
            'doctor_id' => $this->doctor->id,
        ]);

        $this->assertDatabaseHas('doctor_schedules', [
            'doctor_id' => $this->doctor->id,
        ]);
    }


}
